CREATE TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT Reserve(:UserId, :password, :FlightId, :SeatNo);
COMMIT;

CREATE TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT BuyFree(:FlightId, :SeatNo);
COMMIT;

CREATE TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT BuyReserved(:UserId, :password, :FlightId, :SeatNo);
COMMIT;

CREATE TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT ExtendReservation(:UserId, :Password, :FlightId, :SeatNo);
COMMIT;
