StudentsWithMarks(StudentId) :-
    Students(StudentId, StudentName, GroupId),
    Marks(StudentId, CourseId, _),
    CourseId = :CourseId.

StudentsWithCourse(StudentId) :-
    Students(StudentId, StudentName, GroupId),
    Plan(GroupId, CourseId, _),
    CourseId = :CourseId.

Result(StudentId, StudentName, GroupName) :- 
    Students(StudentId, StudentName, GroupId),
    Groups(GroupId, GroupName),
    StudentsWithCourse(StudentId),
    ¬StudentsWithMarks(StudentId).
